---
platform: linux

image: docker:///bosh/main

inputs:
- name: bosh

run:
  path: bosh/ci/tasks/test-integration.sh

params:
  RUBY_VERSION: replace-me
  DB:           replace-me
  LOG_LEVEL:    INFO
  NUM_GROUPS:   8
